objects1 = echo_server_n.o CEchoIO.o
objects2 = echo_client_n.o CEchoIO.o

all : echo_server echo_client

echo_server : $(objects1)
	g++ -g -o  echo_server_n $(objects1) 

echo_client : $(objects2)
	g++ -g -o  echo_client_n $(objects2) 
	

CEchoIO.o : CEchoIO.h

clean:
	rm echo_server_n echo_client_n echo_server_n.o echo_client_n.o CEchoIO.o
